name = "SpectralModels"
uuid = "19d18bf1-850e-46c8-bfb4-a0c3983d0455"
authors = ["brian.e.svoboda@gmail.com"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
